name: "Issue Auto Reply"

on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Add personalized welcome comment
        uses: actions/github-script@v7
        with:
          script: |
            const issueAuthor = context.payload.issue.user.login;
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `👋 Hi @${issueAuthor}, thank you for raising this issue! Our team will review it soon. 
              
            For more queries, discussions, or approval of requests, please join our Discord server: [Discord Link](https://discord.com/invite/Yn9g6KuWyA)`
            })
